// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: entity.sql

package db

import (
	"context"
)

const createEntity = `-- name: CreateEntity :one
INSERT INTO entity_type(
	enty_name )
	VALUES ($1) 
	RETURNING enty_id, enty_name
`

func (q *Queries) CreateEntity(ctx context.Context, entyName string) (*EntityType, error) {
	row := q.db.QueryRow(ctx, createEntity, entyName)
	var i EntityType
	err := row.Scan(&i.EntyID, &i.EntyName)
	return &i, err
}

const deleteEntity = `-- name: DeleteEntity :exec
DELETE FROM entity_type
	WHERE enty_id=$1
    RETURNING enty_id, enty_name
`

func (q *Queries) DeleteEntity(ctx context.Context, entyID int32) error {
	_, err := q.db.Exec(ctx, deleteEntity, entyID)
	return err
}

const findAllEntity = `-- name: FindAllEntity :many
SELECT enty_id, enty_name
	FROM entity_type
`

func (q *Queries) FindAllEntity(ctx context.Context) ([]*EntityType, error) {
	rows, err := q.db.Query(ctx, findAllEntity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*EntityType
	for rows.Next() {
		var i EntityType
		if err := rows.Scan(&i.EntyID, &i.EntyName); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findEntityById = `-- name: FindEntityById :one
SELECT enty_id, enty_name
	FROM entity_type WHERE enty_id=$1
`

func (q *Queries) FindEntityById(ctx context.Context, entyID int32) (*EntityType, error) {
	row := q.db.QueryRow(ctx, findEntityById, entyID)
	var i EntityType
	err := row.Scan(&i.EntyID, &i.EntyName)
	return &i, err
}

const updateEntity = `-- name: UpdateEntity :one
UPDATE entity_type
	SET enty_name=$2
	WHERE enty_id=$1    
    RETURNING enty_id, enty_name
`

type UpdateEntityParams struct {
	EntyID   int32  `json:"enty_id"`
	EntyName string `json:"enty_name"`
}

func (q *Queries) UpdateEntity(ctx context.Context, arg UpdateEntityParams) (*EntityType, error) {
	row := q.db.QueryRow(ctx, updateEntity, arg.EntyID, arg.EntyName)
	var i EntityType
	err := row.Scan(&i.EntyID, &i.EntyName)
	return &i, err
}
