// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type EntityType struct {
	EntyID   int32  `json:"enty_id"`
	EntyName string `json:"enty_name"`
}

type PaymentTransaction struct {
	PatrxNo         string         `json:"patrx_no"`
	PatrxCreatedOn  pgtype.Date    `json:"patrx_created_on"`
	PatrxDebet      pgtype.Numeric `json:"patrx_debet"`
	PatrxCredit     pgtype.Numeric `json:"patrx_credit"`
	PatrxNotes      *string        `json:"patrx_notes"`
	PatrxAcctnoFrom *string        `json:"patrx_acctno_from"`
	PatrxAcctnoTo   *string        `json:"patrx_acctno_to"`
	PatrxPatrxRef   *string        `json:"patrx_patrx_ref"`
	PatrxTratyID    *int32         `json:"patrx_traty_id"`
}

type UserAccount struct {
	UsacID        int32          `json:"usac_id"`
	UsacAccountNo string         `json:"usac_account_no"`
	UsacBalance   pgtype.Numeric `json:"usac_balance"`
	UsacCreatedOn pgtype.Date    `json:"usac_created_on"`
	UsacButyID    *int32         `json:"usac_buty_id"`
	UsacUserID    *int32         `json:"usac_user_id"`
}
